[package]
name = "serial-monitor"
version = "0.0.1"
authors = ["Dave Hylands <dhylands@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.17", features = ["event-stream"] }
futures = { version = "0.3" }
futures-timer = "3.0"
serialport = "3.3.0"
structopt = "0.3"
tokio = { version = "0.2.11", features = ["full"] }
tokio-util = { version = "0.3.1", features = ["codec"] }
tokio-serial = "4.3.3-tokio-0.2.0-alpha.6"
wildmatch = "1.0.6"
