[package]
name = "usb-ser-mon"
version = "0.0.1"
authors = ["Dave Hylands <dhylands@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "3.3.0"
structopt = "0.3"
